CREATE TABLE IF NOT EXISTS customers (
    msisdn TEXT PRIMARY KEY,
    total_transactions INTEGER NOT NULL DEFAULT 0,
    total_spend NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    avg_spend NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    last_seen TIMESTAMP NOT NULL,

    days_since_last INTEGER NOT NULL DEFAULT 0,
    is_churned BOOLEAN NOT NULL DEFAULT FALSE,
    churn_score NUMERIC(4, 2) NOT NULL DEFAULT 0.00,
    loyalty_score NUMERIC(10, 2) NOT NULL DEFAULT 0.00
);

ALTER TABLE customers
ADD COLUMN IF NOT EXISTS first_seen TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS clv NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS r_score INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS f_score INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS m_score NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS customer_segment TEXT NOT NULL DEFAULT 'unknown';


-- remove dummy first seen from TransactionTransformer._update_cummulative_metrics, add it in the table
